### ISSUE TITLE
Make `pyssht` dependency only for tests

### ISSUE THREAD

**Issue by matt-graham** [astro-informatics/s2fft#102]
Thanks for that info @matt-graham .  The precompute stuff is experimental and in future we should use `s2fft` there rather than `ssht`.  So in principle `ssht` could be only a test requirement but we would need to remove it from the precompute functionality.    Perhaps another issue to add to pick up later?

_Originally posted by @jasonmcewen in https://github.com/astro-informatics/s2fft/pull/101#discussion_r1018844362_

**Comment by CosmoMatt** [comment]
This is a floating issue which has been resolved so I'll close it.
