### ISSUE TITLE
Forcing jax float64 mode

### ISSUE THREAD

**Issue by EiffL** [astro-informatics/s2fft#143]
This is not really good practice, users can have legitimate reasons for not using float64 and if they import `s2fft` first, it will force the type without leaving them a choice:
https://github.com/astro-informatics/s2fft/blob/e9e6f78c685d2dd54f6344e29a35de65c09fb350/s2fft/transforms/spherical.py#L3

If you think float64 is really important for this library, you could instead send a warning back if the users have not enabled it.

**Comment by CosmoMatt** [comment]
The problem really starts to become apparent inside the recursions. With 64bit precision, at high L the error can grow from 1e-16 to around 1e-13 or so. With 32bit precision, without accounting for any other factors, this should correspond to an error from around 1e-6 to 1e-3 to even 1e-2, which isn't great.

I think a warning would be a good option around this though, but we will have to be clear that 64bit can be really quite important in this case. This hard coding of 64bit precision comes up throughout several functions, perhaps we should just include a warning at the high-level?

**Comment by EiffL** [comment]
Yep, I'm proposing a solution in #145 Maybe the warning can be evn more ominous ^^

**Comment by CosmoMatt** [comment]
Closing as this was addressed in #145
