### ISSUE TITLE
Forcing a specific version of jax and jaxlib

### ISSUE THREAD

**Issue by EiffL** [astro-informatics/s2fft#144]
I see that the requirements are forcing version 0.3 of jax, is there a good reason for it?

https://github.com/astro-informatics/s2fft/blob/e9e6f78c685d2dd54f6344e29a35de65c09fb350/requirements/requirements-core.txt#L7

In general, you don't want to impose a jax version, as it can cause mannnny compatibility problems. It's ok to impose a minimal version though, like "jax>=0.3.1"

Also, it's good practice not to explicitly impose a requirement on jaxlib, because you typically need to be careful about how you install jaxlib for a particular system and if pip just tries to download a random version it may uninstall a good jaxlib to install a bad jaxlib.

**Comment by CosmoMatt** [comment]
Do you think it would be best to have jax and jaxlib as open requirements then @EiffL ? e.g. remove all versions from requirements-core.txt? If so this should take no time to fix.

**Comment by EiffL** [comment]
A good point of reference is to look at one of Google's own jax packages, like this one:
https://github.com/google/flax/blob/main/setup.py
They only have `jax` as the requirement, and it is ok to add the version number. Because it is very possible that previous version of jax were not working in the same way as the new ones... so the one you currently have is good I think.

**Comment by jasonmcewen** [comment]
Can we keep this pinned but upgrade to 0.4.x?

**Comment by EiffL** [comment]
well the issue is forcing a specific version of jax. JAX is getting a new release like every 2 weeks. If all jax-based libraries imposed a specific version, it would be utterly unmanageable. 

The idea is that all libraries should have a minimum version under which they are not guaranteed to work, and then try to remain up to date with upstream jax. breaking changes are rare these days.

**Comment by EiffL** [comment]
One of the core strengths of jax is all libraries based on it are interoperable. You can grab your favorite optim library (optax, jaxopt, etc) combine it with your favorite NN library (haiku, flax, equinox, etc.). It would be impossible for all of them to agree on just one version of jax to follow.

**Comment by jasonmcewen** [comment]
I see. Ok, let's set a minimum then.

**Comment by CosmoMatt** [comment]
Closing as this was addressed in #145
