### ISSUE TITLE
make plotting requirements optional

### ISSUE THREAD

**Issue by ntessore** [astro-informatics/s2fft#150]
It would be nice if the requirements for plotting, which are quite heavy and pull in lots of other dependencies, could be made an optional extra dependency.

**Comment by CosmoMatt** [comment]
@ntessore I think that's a very fair point, what we could do is move the dependency over to a separate requirements file and partition off the plotting functions from the core package. We are currently exploring an issue which has evolved with other (redundant) requirements, so we can address both issues with a single PR. Links to #151

**Comment by CosmoMatt** [comment]
@ntessore shouldn't be an issue any more!
