### ISSUE TITLE
Wigner slice at poles: division by zero

### ISSUE THREAD

**Issue by PhilippMisofCH** [astro-informatics/s2fft#181]
Hey!

While playing around with the `s2fft.recursions.price_mcewen.compute_all_slices_jax` function I noticed that the case $\beta \in \{ 0,\pi \}$ is not handled since it leads to division by `s = ` $\sin(0) = \sin(\pi) = 0$:

https://github.com/astro-informatics/s2fft/blob/2d2370fbca0cee70b6cfcdbab333a8ddf90425e6/s2fft/recursions/price_mcewen.py#L567

https://github.com/astro-informatics/s2fft/blob/2d2370fbca0cee70b6cfcdbab333a8ddf90425e6/s2fft/recursions/price_mcewen.py#L598

I would expect that the analytical results of http://arxiv.org/abs/2311.14670, eq. 28 & 29 are implemented, or did I miss something?

Thanks in advance!

**Comment by CosmoMatt** [comment]
Hey @PhilippMisofCH great catch. This function doesn't seem to explicitly compute the north and South Pole singularities, so this is something we might want to add. Note that when performing the spherical harmonic (or Wigner) transforms a [modified version](https://github.com/astro-informatics/s2fft/blob/2d2370fbca0cee70b6cfcdbab333a8ddf90425e6/s2fft/transforms/otf_recursions.py) of the recursion is run which does [handle](https://github.com/astro-informatics/s2fft/blob/2d2370fbca0cee70b6cfcdbab333a8ddf90425e6/s2fft/transforms/otf_recursions.py#L389) these singularities correctly.

The function we ported over into `s2fft.recursions.price_mcewen.compute_all_slices_jax` was predominately for testing purposes and in case anyone wanted to create the full set of Wigner matrices. If you think it would be useful I can explicitly enter the north/South Pole values?

**Comment by PhilippMisofCH** [comment]
Ah that's what I've suspected. Thanks a lot for the quick reply. In fact I'm using your library to construct the Wigner matrices explicitly since I'm doing a rotation of a function on a sphere via Fourier space operations where the $\mathcal{D}^l_{mn}$ pops up. I also plan to use them for other relations. So yes I would need the functionality but I don't expect this to be of any priority to you. Of course I would be glad if you implement the poles but I can also try to do that myself and issue a pull request afterwards. Let me know.

**Comment by CosmoMatt** [comment]
No worries. In the meantime the functionality from our previous code `ssht` found [here](https://github.com/astro-informatics/ssht/blob/c83fb2a07e1869e875e819523d2e19d91bc8a4bf/src/pyssht/cpyssht.pyx#L2650) may be of use, provided you don't need these rotations to be differentiable?

**Comment by PhilippMisofCH** [comment]
No, at the moment I don't need differentiability for that. Thanks for the link, I will have a look into that!

**Comment by jasonmcewen** [comment]
Thanks for highlighting this @PhilippMisofCH !

@CosmoMatt could you add this in our standalone recursions when you get a chance?  Just as @PhilippMisofCH has run into this, I suspect others might also so would be good to support the special cases here too.  I'm not certain we need to handle these special cases for the Risbo recurions in #182 tho.  See my comments on that PR.

**Comment by PhilippMisofCH** [comment]
Yes I've noticed. Thanks a lot!!
