### ISSUE TITLE
Complex to float conversion warnings; errors when disabling jax's jit regarding int to float conversion

### ISSUE THREAD

**Issue by PhilippMisofCH** [astro-informatics/s2fft#183]
Hey, it's me again.

While working with this library and debugging some of my code I found the following small issues which can lead to errors in future versions of jax

Note that some of the issues only appear when running jax with `config.update("jax_disable_jit", True)`

https://github.com/astro-informatics/s2fft/blob/26ff37a8e05bab8adc31dd9efc3c73081ebed8ff/s2fft/utils/rotation.py#L37-L40

I think `dl` should be of type `jnp.float64` because the $d$ matrix is real and is also implemented as `float64` in `risbo.py`, otherwise I get warnings that the `complex128` to `float64` conversion is deprecated and will become an error in the next update.

A few times there is a `(-1)` taken to a negative power which issues an error when jax's jit is disabled
https://github.com/astro-informatics/s2fft/blob/26ff37a8e05bab8adc31dd9efc3c73081ebed8ff/s2fft/transforms/spherical.py#L299
https://github.com/astro-informatics/s2fft/blob/26ff37a8e05bab8adc31dd9efc3c73081ebed8ff/s2fft/transforms/spherical.py#L660
https://github.com/astro-informatics/s2fft/blob/26ff37a8e05bab8adc31dd9efc3c73081ebed8ff/s2fft/transforms/wigner.py#L262
**Suggestion:** substitute `(-1)` with `(-1.0)`

I get another warning about an invalid escape sequence `\e`
https://github.com/astro-informatics/s2fft/blob/26ff37a8e05bab8adc31dd9efc3c73081ebed8ff/s2fft/recursions/risbo.py#L106-L114
**Suggestion:** make it a raw string literal with `r"""...`

Btw thanks a lot for the `rotate_flm` implementation, it is exactly what I needed.

**Comment by CosmoMatt** [comment]
Hi again 👋 thanks for the debugging, definitely correct about the Wigner matrices. I'll work through these points today and update the codebase ready for v1.0.2 release.

**Comment by CosmoMatt** [comment]
Closing as this should have been addressed in PR #189
