### ISSUE TITLE
Add support for Gauss-Legendre(gl) sampling

### ISSUE THREAD

**Issue by yangjinhui11** [astro-informatics/s2fft#184]
The era5 analysis data set uses the gl sampling

**Comment by CosmoMatt** [comment]
Hi @yangjinhui11, I can't say we're familiar with the era5 data but we're definitely aware of GL sampling. I'll pick this issue up today and get some GL sampling support into the package.

**Comment by yangjinhui11** [comment]
There is an error in Eq(46), in you paper which describ the GL quadrature weights.  It sin^2 \theta shoud in denominator.  See https://mathworld.wolfram.com/Legendre-GaussQuadrature.html

I implement the GL sampling in the following way. It looks like it works
`nlon=L*2-1`
`cost,w =np.legendre_gauss_weights(L)`
`thetas = jnp.flip(np.arccos(cost))`
`weights=jnp.array(w)* jnp.pi/nlon`

Then pass the thetas and weights to forward_jax, and inverse_jax.

**Comment by CosmoMatt** [comment]
@yangjinhui11 We've added support for GL sampling to v1.0.2 which was merged into main in PR #193. We'll make a new PyPi release now so you can pick up this functionality!
