### ISSUE TITLE
Bump repository version/release?

### ISSUE THREAD

**Issue by lgrcia** [astro-informatics/s2fft#188]
I am interested in using `utils.rotation` which isn't in the `1.0.1` release. Would it be possible to bump the version in `setup.py` to reflect the state of the repository? Or even better, have a new release with these utils? 

That's very much a detail and for now I will just use a clone of the repository. Looking forward using the package!

**Comment by CosmoMatt** [comment]
Hi @lgrcia great to hear these rotations are being used! I'm currently picking up floating issues and am planning to make a v1.0.2 release either later today or tomorrow. I'll let you know when its live and we can wrap up this issue.

**Comment by lgrcia** [comment]
That's great, so is this all package. I will open another issue regarding some of the rotation utils. Thanks a lot for the good work here!
