### ISSUE TITLE
Static polar angle in ‎`utils.rotation.generate_rotate_dls`

### ISSUE THREAD

**Issue by lgrcia** [astro-informatics/s2fft#191]
Is there a reason why the angle `beta` is made static in [utils.rotation.generate_rotate_dls](https://github.com/astro-informatics/s2fft/blob/f17ac17c04466c9848d45e0d4b9005b3aa1460a3/s2fft/utils/rotation.py#L75) and [recursions.risbo_jax.compute_full](https://github.com/astro-informatics/s2fft/blob/f17ac17c04466c9848d45e0d4b9005b3aa1460a3/s2fft/recursions/risbo_jax.py#L7)? It seems that these functions can deal with an ArrayLike value but I might miss the bigger picture.

**Comment by CosmoMatt** [comment]
Hi @lgrcia no reason in particular, in theory you could run this in a batched manner (over beta) and compute all rotation matrices at the same time. The catch is that you end up getting O(L^4) memory and compute that way -- as you'd have to store the Wigner matrices for all el (0-L) m (-el, el) n (-el, el) and beta (0-L).

The better way to go about things is to compute the rotate matrices for beta = pi/2 and then use the Fourier relation between the Wigner coefficients to generate all other beta values -- see equation 8 of [this](https://arxiv.org/pdf/1110.6298.pdf) paper. Then the idea is to compute the rotation matrices once then use this relation to read off all other rotations with O(L^3) memory and compute.

Hope this helps, and if you still want the option to pass many beta values we can certainly make it non-static and support vectoring over beta, just let me know and I can add it to my list!

**Comment by lgrcia** [comment]
I think the new version of `s2fft` perfectly fits our needs. I am happy to have this issue closed. I will get in touch about the suggestion you made. Thanks a lot for the support here!
