### ISSUE TITLE
Decide on a code style convention and set-up automatic formatting

### ISSUE THREAD

**Issue by matt-graham** [astro-informatics/s2fft#205]
We don't currently specify the code style convention we want the package code to adhere to. Ideally we should settle on something and document this to make it easy for contributors to know what to target when proposing changes and to ensure we are consistent across the repository to improve readability. This has come up as part of @ASKabalan's contributions in #204.

Currently I think we are mainly following [PEP8 guidelines](https://peps.python.org/pep-0008/) and this is probably the most commonly used convention in open-source Python projects so I would personally suggest adopting this. Alternatives include the [Google Python style guide](https://google.github.io/styleguide/pyguide.html).

Related to this, to simplify keeping to a standard style, it would be good to adopt a specific formatter which enforces our chosen style conventions - as an additional check as part of the CI workflows and/or by setting up [`pre-commit` hooks](https://pre-commit.com/) to automatically run the formatter on any commits. My suggestion for a formatter would be [the Ruff formatter](https://docs.astral.sh/ruff/formatter/) as its very performant so minimizes overhead when formatting and uses the same formatting rules as [Black ](https://github.com/psf/black) which is widely used. 

Tagging @jasonmcewen and @CosmoMatt for their views.

**Comment by ASKabalan** [comment]
I am ok with any formatter.
[the Ruff formatter](https://docs.astral.sh/ruff/formatter/) seems ok for me

**Comment by ASKabalan** [comment]
I also add the fact that I chose a c++ formatter to be [google](https://github.com/astro-informatics/s2fft/blob/cufft-primitive/.clang-format)  using [LSST guidelines](https://developer.lsst.io/cpp/clang-format.html#general)

**Comment by matt-graham** [comment]
@jasonmcewen, @CosmoMatt and myself discussed this in a meeting today and there was a consesus for using the [Black code style](https://black.readthedocs.io/en/stable/the_black_code_style/index.html).

**Comment by jasonmcewen** [comment]
Thanks @matt-graham.  Yes, since we're using Black in other codes and its fairly common for Python we thought we should go with that.  We have been using Black already with s2fft I belive, although perhaps not extensively.  We should indeed try to get this fully set up and specified in any contributor guidelines.
